#! /bin/bash
PROTOC=../../../../../../../third-64/protobuf/bin/protoc
#PROTOC=../../../../../../../third-64/protobuf-2.6.0/protobuf/bin/protoc
if [ ! -x $PROTOC ]
then
	echo "protoc not exist"
	exit 0
fi

for proto in `ls *.proto`
do
	$PROTOC -I=. --cpp_out=. $proto
done

echo "// Generated by build.sh script.  DO NOT EDIT !" > user_proto.h
echo "#ifndef _PBRPCPRESS_USER_PROTO_H_" >> user_proto.h
echo "#define _PBRPCPRESS_USER_PROTO_H_" >> user_proto.h

for pbh in `ls *.pb.h`
do
	echo "#include \"$pbh\"" >> user_proto.h
done

echo "#endif //_PBRPCPRESS_USER_PROTO_H_" >> user_proto.h
